all: demo01 demo02 demo03
demo01: demo01.cpp
	g++ -g -o demo01 demo01.cpp -lpthread
demo02: demo02.cpp
	g++ -g -o demo02 demo02.cpp -lpthread
demo03: demo03.cpp
	g++ -g -o demo03 demo03.cpp
clean:
	rm -r demo01 demo02 demo03
