all: demo01 demo02 demo03 demo04 demo05 demo06
demo01: demo01.c
	gcc -g -o demo01 demo01.c
demo02: demo02.c
	gcc -g -o demo02 demo02.c
demo03: demo03.cpp
	g++ -g -o demo03 demo03.cpp -lpthread
demo04: demo04.cpp
	g++ -g -o demo04 demo04.cpp
demo05: demo05.cpp
	g++ -g -o demo05 demo05.cpp
demo06: demo06.cpp
	g++ -g -o demo06 demo06.cpp
clean:
	rm -rf bin/*
	rm -rf demo01 demo02 demo03 demo04 demo05 demo06
